Update CodeOfConduct.md
DaanMatch/Administrivia pull request #4
Opened 2022-01-31 22:45 UTC by biofool

Was thinking about comms training for the interns and thought these couple of sentences helped.

2022-02-06 22:55 UTC, shpatrickguo requested changes
Small spelling things.

2022-02-06 22:55 UTC, shpatrickguo commented on CodeOfConduct.md
> +We believe everyone who acts in a way that supports their own self interest and the community self interest is a leader.
We believe everyone who acts in a way that supports their own self-interest and the community's self-interest is a leader.

2022-02-06 22:55 UTC, shpatrickguo commented on CodeOfConduct.md
> +We belive that every mistake is an opportunit to learn.
We believe that every mistake is an opportunity to learn.

2022-02-16 02:41 UTC, biofool reviewed
Looks fine.

2022-02-16 02:41 UTC, merged

2023-05-26 23:36 UTC, biofool commented
!